# 🌦️ Weather Data Analysis of India

### Problem Statement
The project analyzes multi-year historical climate data across `24 major cities` representing all geographic regions of India to capture nationwide weather variability. Using multi-variable meteorological data, the study `identifies long-term climate trends, regional seasonal patterns, and extreme weather events such as heatwaves and heavy rainfall`. The project also examines `interactions between atmospheric, hydrological, and land-surface variables to understand climate system behavior`. The goal is to build data-driven insights and risk indicators to support climate monitoring and environmental analysis.

# 🇮🇳 Cities Covered — Grouped by Region

## 🧭 North India
- Delhi
- Srinagar
- Ladakh
- Amritsar
- Manali
- Nainital
- Lucknow

## 🌅 East India
- Patna
- Kolkata (Calcutta)

## 🌧️ Northeast India
- Guwahati
- Agartala
- Geku

## 🌵 West India
- Ahmedabad
- Jaisalmer
- Mumbai

## 🌾 Central India
- Kota
- Jabalpur
- Nagpur

## 🌴 South India
- Chennai
- Bengaluru
- Hyderabad
- Visakhapatnam
- Udupi
- Thiruvananthapuram

---

### 📌 Notes
- Cities are grouped based on broad geographic regions used in climatology and weather analysis.
- Some locations (e.g., **Ladakh**) represent larger geographic regions rather than a single city.
- Kolkata and Calcutta refer to the same city; the modern name **Kolkata** is used here.

# 🪨 Column Descriptions

| Variable | Unit | Description |
|---|---|---|
| **time** | ISO8601 (date) | Date of the observation (daily timestamp). |
| **weather_code** | WMO code | The most severe weather condition on a given day |
| **temperature_2m_max** | °C | Maximum daily air temperature at 2 meters above ground |
| **temperature_2m_min** | °C | Minimum daily air temperature at 2 meters above ground |
| **temperature_2m_mean** | °C | Mean daily air temperature at 2 meters above ground (daily average). |
| **apparent_temperature_max** | °C | Maximum daily apparent (feels-like) temperature |
| **apparent_temperature_min** | °C | Minimum daily apparent (feels-like) temperature |
| **sunshine_duration** | seconds | Number of seconds of sunshine per day (direct irradiance > 120 W/m², WMO definition). This is typically less than daylight duration due to dawn and dusk. |
| **daylight_duration** | seconds | Total number of daylight seconds per day |
| **sunrise** | ISO8601 | Sunrise time |
| **sunset** | ISO8601 | Sunset time |
| **precipitation_sum** | mm | Total daily precipitation (rain, showers, and snowfall) |
| **rain_sum** | mm | Total daily rainfall |
| **snowfall_sum** | cm | Total daily snowfall |
| **precipitation_hours** | hours | Number of hours with precipitation |
| **shortwave_radiation_sum** | MJ/m² | Total daily incoming shortwave solar radiation |
| **wind_direction_10m_dominant** | ° | Dominant wind direction |
| **wind_speed_10m_max** | km/h | Maximum wind speed at 10 meters above ground |
| **wind_speed_10m_min** | km/h | Minimum daily wind speed at 10 meters above ground |
| **wind_speed_10m_mean** | km/h | Mean daily wind speed at 10 meters above ground |
| **et0_fao_evapotranspiration** | mm | Daily reference evapotranspiration (ET₀) for a well-watered grass field (FAO standard) |
| **cloud_cover_max** | % | Maximum total cloud cover during the day (0–100%). |
| **cloud_cover_min** | % | Minimum total cloud cover during the day (0–100%). |
| **cloud_cover_mean** | % | Mean daily total cloud cover (0–100%). |
| **soil_moisture_0_to_100cm_mean** | m³/m³ | Mean volumetric soil water content averaged from surface to 100 cm depth. |
| **soil_temperature_0_to_100cm_mean** | °C | Mean soil temperature averaged from surface to 100 cm depth. |
| **dew_point_2m_min** | °C | Minimum daily dew point temperature at 2 meters above ground. |
| **dew_point_2m_max** | °C | Maximum daily dew point temperature at 2 meters above ground. |
| **dew_point_2m_mean** | °C | Mean daily dew point temperature at 2 meters above ground. |
| **wet_bulb_temperature_2m_min** | °C | Minimum daily wet-bulb temperature at 2 meters above ground. |
| **wet_bulb_temperature_2m_max** | °C | Maximum daily wet-bulb temperature at 2 meters above ground. |
| **wet_bulb_temperature_2m_mean** | °C | Mean daily wet-bulb temperature at 2 meters above ground. |
| **relative_humidity_2m_min** | % | Minimum daily relative humidity at 2 meters above ground. |
| **relative_humidity_2m_max** | % | Maximum daily relative humidity at 2 meters above ground. |
| **relative_humidity_2m_mean** | % | Mean daily relative humidity at 2 meters above ground. |
| **surface_pressure_min** | hPa | Minimum daily surface air pressure. |
| **surface_pressure_max** | hPa | Maximum daily surface air pressure. |
| **pressure_msl_min** | hPa | Minimum daily mean sea-level pressure (MSL). |
| **pressure_msl_max** | hPa | Maximum daily mean sea-level pressure (MSL). |
| **pressure_msl_mean** | hPa | Mean daily mean sea-level pressure (MSL). |
| **latitude** | decimal degrees | Latitude of the location. |
| **longitude** | decimal degrees | Longitude of the location. |
| **location_id** | — | Unique identifier assigned to each location in the dataset. |

---

## 📌 Notes
- Temperature values are measured at **2 meters** above ground level.  
- Wind values are measured at **10 meters** above ground level.  
- Times are provided in **ISO 8601** format.  
- Cloud cover is expressed as **percentage of sky covered by clouds (0–100%)**.  
- Soil variables represent **layer-averaged values from 0–100 cm depth**.

In [67]:
# Library imports
import pandas as pd

### Combine the 3 dataframes into one and export as a single file

In [68]:
df_part1= pd.read_csv(r'weather_data_7_locations.csv')
df_part2= pd.read_csv(r'weather_data_8_locations.csv')
df_part3= pd.read_csv(r'weather_data_9_locations.csv')


# On viewing the csv, we find that df_part1 is of the format yyyy-mm-dd and df_part2 and df_part3 are both of the format dd-mm-yyyy.
# So we convert df_part1 to match the format of the other two and the merge them into single dataset

df_part1["time"] = pd.to_datetime(df_part1["time"], format="%Y-%m-%d")
df_part1["time"] = df_part1["time"].dt.strftime("%d-%m-%Y")                 # convert format to dd-mm-yyyy
df_part1.head()

,time,weather_code,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,sunshine_duration,daylight_duration,sunrise,sunset,...,relative_humidity_2m_mean,soil_temperature_0_to_100cm_mean,wind_speed_10m_min,wind_speed_10m_mean,wet_bulb_temperature_2m_min,wet_bulb_temperature_2m_max,wet_bulb_temperature_2m_mean,latitude,longitude,location_id
0,01-01-2018,0,24.4,11.4,23.5,10.1,35208.99,38161.03,2018-01-01T07:12,2018-01-01T17:48,...,56,21.0,2.4,7.0,8.9,15.4,11.6,25.202108,75.80994,1
1,02-01-2018,0,22.8,8.6,20.5,7.1,35233.59,38183.40,2018-01-02T07:12,2018-01-02T17:48,...,56,20.8,3.2,5.9,7.5,12.4,9.8,25.202108,75.80994,1
2,03-01-2018,0,22.9,10.3,20.4,8.2,35260.27,38207.68,2018-01-03T07:12,2018-01-03T17:49,...,55,20.5,1.6,6.0,7.6,12.0,9.7,25.202108,75.80994,1
3,04-01-2018,0,24.4,8.1,22.0,5.7,35289.14,38233.86,2018-01-04T07:12,2018-01-04T17:50,...,56,20.3,2.6,7.6,7.0,12.9,10.1,25.202108,75.80994,1
4,05-01-2018,0,24.0,9.9,22.4,8.7,35320.67,38262.24,2018-01-05T07:13,2018-01-05T17:50,...,58,20.2,1.3,5.2,8.5,14.3,11.2,25.202108,75.80994,1

In [69]:
# Now we can merge all 3 df_parts into one single dataset 
combined_df= pd.concat([df_part1, df_part2, df_part3], ignore_index= True)
print("The dataset has been combined into a single dataset with", combined_df.shape[0], "rows")

# export the combined dataset
# combined_df.to_csv('complete_weather_data.csv', index= False)

The dataset has been combined into a single dataset with 80000 rows

# ▶️ Import combined dataset

In [104]:
# Import the complete combined dataset
df= pd.read_csv(r'complete_weather_data.csv')
df.head(10)

,time,weather_code,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,sunshine_duration,daylight_duration,sunrise,sunset,...,relative_humidity_2m_mean,soil_temperature_0_to_100cm_mean,wind_speed_10m_min,wind_speed_10m_mean,wet_bulb_temperature_2m_min,wet_bulb_temperature_2m_max,wet_bulb_temperature_2m_mean,latitude,longitude,location_id
0,01-01-2018,0,24.4,11.4,23.5,10.1,35208.99,38161.03,2018-01-01T07:12,2018-01-01T17:48,...,56.0,21.0,2.4,7.0,8.9,15.4,11.6,25.202108,75.80994,1
1,02-01-2018,0,22.8,8.6,20.5,7.1,35233.59,38183.40,2018-01-02T07:12,2018-01-02T17:48,...,56.0,20.8,3.2,5.9,7.5,12.4,9.8,25.202108,75.80994,1
2,03-01-2018,0,22.9,10.3,20.4,8.2,35260.27,38207.68,2018-01-03T07:12,2018-01-03T17:49,...,55.0,20.5,1.6,6.0,7.6,12.0,9.7,25.202108,75.80994,1
3,04-01-2018,0,24.4,8.1,22.0,5.7,35289.14,38233.86,2018-01-04T07:12,2018-01-04T17:50,...,56.0,20.3,2.6,7.6,7.0,12.9,10.1,25.202108,75.80994,1
4,05-01-2018,0,24.0,9.9,22.4,8.7,35320.67,38262.24,2018-01-05T07:13,2018-01-05T17:50,...,58.0,20.2,1.3,5.2,8.5,14.3,11.2,25.202108,75.80994,1
5,06-01-2018,0,23.8,10.6,22.1,10.3,35354.65,38292.87,2018-01-06T07:13,2018-01-06T17:51,...,59.0,20.2,0.4,4.8,9.9,13.6,11.2,25.202108,75.80994,1
6,07-01-2018,0,23.4,9.4,21.8,8.0,35391.00,38325.67,2018-01-07T07:13,2018-01-07T17:52,...,52.0,20.2,0.8,4.5,7.9,12.8,10.4,25.202108,75.80994,1
7,08-01-2018,0,23.5,9.2,21.5,7.0,35429.62,38360.57,2018-01-08T07:13,2018-01-08T17:52,...,50.0,20.2,1.3,5.2,7.3,12.6,10.0,25.202108,75.80994,1
8,09-01-2018,0,24.0,10.2,22.0,8.6,35470.45,38397.51,2018-01-09T07:13,2018-01-09T17:53,...,50.0,20.1,2.9,5.2,8.0,12.9,10.2,25.202108,75.80994,1
9,10-01-2018,0,24.3,10.5,21.9,9.5,35505.58,38436.40,2018-01-10T07:13,2018-01-10T17:54,...,46.0,20.0,1.0,3.3,8.8,12.9,10.6,25.202108,75.80994,1

In [105]:
# Check data type of time column
df['time'].dtype

In [106]:
# Convert 'time' column from String to DateTime
df['time']= pd.to_datetime(df['time'], format="%d-%m-%Y")
df['time'].dtype

dtype('<M8[us]')

In [107]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 43 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   time                              80000 non-null  datetime64[us]
 1   weather_code                      80000 non-null  int64
 2   temperature_2m_max                80000 non-null  float64
 3   temperature_2m_min                80000 non-null  float64
 4   apparent_temperature_max          80000 non-null  float64
 5   apparent_temperature_min          80000 non-null  float64
 6   sunshine_duration                 80000 non-null  float64
 7   daylight_duration                 80000 non-null  float64
 8   sunrise                           80000 non-null  str
 9   sunset                            80000 non-null  str
 10  precipitation_sum                 80000 non-null  float64
 11  rain_sum                          80000 non-null  float64
 12  snowfall_sum                      80000 non-null  float64
 13  precipitation_hours               80000 non-null  float64
 14  shortwave_radiation_sum           80000 non-null  float64
 15  wind_direction_10m_dominant       80000 non-null  int64
 16  wind_speed_10m_max                80000 non-null  float64
 17  et0_fao_evapotranspiration        80000 non-null  float64
 18  cloud_cover_max                   80000 non-null  int64
 19  cloud_cover_min                   80000 non-null  int64
 20  temperature_2m_mean               80000 non-null  float64
 21  cloud_cover_mean                  80000 non-null  int64
 22  soil_moisture_0_to_100cm_mean     80000 non-null  float64
 23  dew_point_2m_mean                 80000 non-null  float64
 24  dew_point_2m_max                  80000 non-null  float64
 25  dew_point_2m_min                  80000 non-null  float64
 26  surface_pressure_min              80000 non-null  float64
 27  surface_pressure_max              80000 non-null  float64
 28  pressure_msl_min                  80000 non-null  float64
 29  pressure_msl_max                  80000 non-null  float64
 30  pressure_msl_mean                 80000 non-null  float64
 31  relative_humidity_2m_min          80000 non-null  int64
 32  relative_humidity_2m_max          80000 non-null  int64
 33  relative_humidity_2m_mean         50776 non-null  float64
 34  soil_temperature_0_to_100cm_mean  80000 non-null  float64
 35  wind_speed_10m_min                80000 non-null  float64
 36  wind_speed_10m_mean               80000 non-null  float64
 37  wet_bulb_temperature_2m_min       80000 non-null  float64
 38  wet_bulb_temperature_2m_max       80000 non-null  float64
 39  wet_bulb_temperature_2m_mean      80000 non-null  float64
 40  latitude                          80000 non-null  float64
 41  longitude                         80000 non-null  float64
 42  location_id                       80000 non-null  int64
dtypes: datetime64[us](1), float64(32), int64(8), str(2)
memory usage: 26.2 MB

> We can see that relative_humidity_2m_mean has around 30k null values. Let us confirm it too

In [108]:
df.isna().sum()

time                                    0
weather_code                            0
temperature_2m_max                      0
temperature_2m_min                      0
apparent_temperature_max                0
apparent_temperature_min                0
sunshine_duration                       0
daylight_duration                       0
sunrise                                 0
sunset                                  0
precipitation_sum                       0
rain_sum                                0
snowfall_sum                            0
precipitation_hours                     0
shortwave_radiation_sum                 0
wind_direction_10m_dominant             0
wind_speed_10m_max                      0
et0_fao_evapotranspiration              0
cloud_cover_max                         0
cloud_cover_min                         0
temperature_2m_mean                     0
cloud_cover_mean                        0
soil_moisture_0_to_100cm_mean           0
dew_point_2m_mean                       0
dew_point_2m_max                        0
dew_point_2m_min                        0
surface_pressure_min                    0
surface_pressure_max                    0
pressure_msl_min                        0
pressure_msl_max                        0
pressure_msl_mean                       0
relative_humidity_2m_min                0
relative_humidity_2m_max                0
relative_humidity_2m_mean           29224
soil_temperature_0_to_100cm_mean        0
wind_speed_10m_min                      0
wind_speed_10m_mean                     0
wet_bulb_temperature_2m_min             0
wet_bulb_temperature_2m_max             0
wet_bulb_temperature_2m_mean            0
latitude                                0
longitude                               0
location_id                             0
dtype: int64

> The only column with null values is 'relative_humidity_2m' with 29224 missing values

Since we do not have hourly values, so we cannot calculate the true mean value for each day. Also we cannot drop the null rows because we would almost lose **37%** of the data. The best way to go around is to make an estimation and since we have columns for **min and max humidity** so we can calculate an estimate mean value using the following formula:

>**mean = (max+min)/2**

This is valid because **min <= mean <= max**

In [109]:
df['relative_humidity_2m_mean'] = df['relative_humidity_2m_mean'].fillna((df['relative_humidity_2m_max']-df['relative_humidity_2m_min']) / 2)

# check null values again
print("Null values in 'relative_humidity_2m_mean':", df['relative_humidity_2m_mean'].isna().sum())
print("Null values in dataset:", df.isna().sum().sum())

Null values in 'relative_humidity_2m_mean': 0
Null values in dataset: 0

> Now we can see that there are no null values left in **relative_humidity_2m_mean** column and in whole table

In [110]:
# Rename 'time' as 'date' and set it as index of the dataset
df.rename(columns= {'time' : 'date'}, inplace= True)
df.set_index('date', inplace= True)

In [111]:
# Check if 'date' is set as index
df.index.name

'date'

In [112]:
# Check if there are any missing day in the dataset

full_index = pd.date_range(start=df.index.min(), end=df.index.max(), freq='D')
missing_timestamps = full_index.difference(df.index)
print('Expected days:', len(full_index))
print('Actual rows:', len(df))
print('Missing timestamps count:', len(missing_timestamps))

Expected days: 3653
Actual rows: 80000
Missing timestamps count: 0

> There are no missing records for any day over 10 years' data for each city

In [113]:
df['sunshine_duration']

date
2018-01-01    35208.99
2018-01-02    35233.59
2018-01-03    35260.27
2018-01-04    35289.14
2018-01-05    35320.67
                ...
2025-12-27    35425.53
2025-12-28    35460.70
2025-12-29    35496.11
2025-12-30    35531.70
2025-12-31    35567.36
Name: sunshine_duration, Length: 80000, dtype: float64

In [114]:
# Convert 'sunlight_duration' and 'daylight_duration' from seconds to hours for each day

df['sunshine_duration'] = df['sunshine_duration'] / 3600
df['daylight_duration'] = df['daylight_duration'] / 3600
df['sunshine_duration']

date
2018-01-01    9.780275
2018-01-02    9.787108
2018-01-03    9.794519
2018-01-04    9.802539
2018-01-05    9.811297
                ...
2025-12-27    9.840425
2025-12-28    9.850194
2025-12-29    9.860031
2025-12-30    9.869917
2025-12-31    9.879822
Name: sunshine_duration, Length: 80000, dtype: float64

In [115]:
df[['sunset', 'sunrise']]

                      sunset           sunrise
date
2018-01-01  2018-01-01T17:48  2018-01-01T07:12
2018-01-02  2018-01-02T17:48  2018-01-02T07:12
2018-01-03  2018-01-03T17:49  2018-01-03T07:12
2018-01-04  2018-01-04T17:50  2018-01-04T07:12
2018-01-05  2018-01-05T17:50  2018-01-05T07:13
...                      ...               ...
2025-12-27  2025-12-27T17:40  2025-12-27T06:49
2025-12-28  2025-12-28T17:40  2025-12-28T06:49
2025-12-29  2025-12-29T17:41  2025-12-29T06:49
2025-12-30  2025-12-30T17:42  2025-12-30T06:50
2025-12-31  2025-12-31T17:42  2025-12-31T06:50

[80000 rows x 2 columns]

> Sunset time has date which is getting redundant as we already have `date` as a separate column. So let's remove the date from the `sunset` column and set it as `datetime` data type. We do the same for 'sunrise' column as well

In [116]:
# Convert type to datetime and extract only the time and remove date from the values

df['sunrise'] = pd.to_datetime(df['sunrise']).dt.strftime('%H:%M')
df['sunset'] = pd.to_datetime(df['sunset']).dt.strftime('%H:%M')

df[['sunrise', 'sunset']]

           sunrise sunset
date
2018-01-01   07:12  17:48
2018-01-02   07:12  17:48
2018-01-03   07:12  17:49
2018-01-04   07:12  17:50
2018-01-05   07:13  17:50
...            ...    ...
2025-12-27   06:49  17:40
2025-12-28   06:49  17:40
2025-12-29   06:49  17:41
2025-12-30   06:50  17:42
2025-12-31   06:50  17:42

[80000 rows x 2 columns]

> We also see that on combining the 3 different parts of main dataset, we get unsorted data with respect to 'date'. So let us sort the dataset as per 'date' for each record

In [117]:
df= df.sort_index()
df.head()

,weather_code,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,sunshine_duration,daylight_duration,sunrise,sunset,precipitation_sum,...,relative_humidity_2m_mean,soil_temperature_0_to_100cm_mean,wind_speed_10m_min,wind_speed_10m_mean,wet_bulb_temperature_2m_min,wet_bulb_temperature_2m_max,wet_bulb_temperature_2m_mean,latitude,longitude,location_id
date,,,,,,,,,,,,,,,,,,,,,
2016-01-01,3,23.4,10.4,24.1,9.4,9.481967,10.483414,06:54,17:23,0.0,...,26.5,20.8,0.5,5.8,9.9,16.1,13.1,26.818980,80.93023,6
2016-01-01,3,25.6,13.5,24.0,12.9,10.366233,11.375169,06:41,18:04,0.0,...,69.0,21.9,7.9,12.6,12.7,16.5,14.8,12.970123,77.56364,5
2016-01-01,3,6.4,-3.3,2.8,-7.6,8.125781,10.080264,07:22,17:26,0.0,...,10.0,6.7,1.1,3.1,-6.8,0.9,-3.9,32.161686,77.15840,4
2016-01-01,3,19.8,8.9,18.3,7.3,9.217025,10.124981,07:29,17:37,0.0,...,21.5,16.3,0.4,3.8,7.5,12.9,9.9,31.599297,74.91018,3
2016-01-01,0,32.8,19.8,35.1,20.3,10.051794,11.001144,07:11,18:11,0.0,...,57.0,27.8,0.4,8.9,16.9,22.2,19.5,19.086115,72.85291,2